// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xgxykliosanrnciwgmjz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhneHlrbGlvc2Fucm5jaXdnbWp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1ODA4MjksImV4cCI6MjA2MTE1NjgyOX0.6Z0MFZ4rjcLFOnuJjg4vPCcJt19ZkMXIB7KJ0NDHgWc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);